### ISSUE TITLE
Conquer error 

### ISSUE THREAD

**Issue by ArisJimenez** [roderickslieker/CONQUER#1]
Hi, 
I have tried to install this package and it gives me this error 

`devtools::install_github("roderickslieker/CONQUER.DB")
Downloading GitHub repo roderickslieker/CONQUER.DB@master
roderickslieker-CONQUER.db-f421da6/data/Skin_Not_Sun_Exposed_Suprapubic.rda: truncated gzip input
tar.exe: Error exit delayed from previous errors.
Error: Failed to install 'conquer.db' from GitHub:
  Does not appear to be an R package (no DESCRIPTION)
Además: Warning messages:
1: In utils::untar(tarfile, ...) :
  ‘tar.exe -xf "C:\Users\ARISDI~1\AppData\Local\Temp\RtmpA7rGkL\filea7682c622317.tar.gz" -C "C:/Users/ARISDI~1/AppData/Local/Temp/RtmpA7rGkL/remotesa7683e733043"’ returned error code 1
2: In system(cmd, intern = TRUE) :
  comando ejecutado 'tar.exe -tf "C:\Users\ARISDI~1\AppData\Local\Temp\RtmpA7rGkL\filea7682c622317.tar.gz"' tiene estatus 1`

**Comment by gerardbouland2** [comment]
Hi ArisJimenez,

It seems that your download was interrupted, as such, it tried to install an incomplete package. I had a similar error when my internet connection was lost for a moment. 

```
Downloading GitHub repo roderickslieker/CONQUER.DB@master
roderickslieker-CONQUER.db-0039417/data/Brain_Hypothalamus.rda: truncated gzip input
tar.exe: Error exit delayed from previous errors.
Error: Failed to install 'conquer.db' from GitHub:
  Does not appear to be an R package (no DESCRIPTION)
In addition: Warning messages:
1: In utils::untar(tarfile, ...) :
  ‘tar.exe -xf "C:\Users\Gerar\AppData\Local\Temp\RtmpCCrbYX\file21e077966d89.tar.gz" -C "C:/Users/Gerar/AppData/Local/Temp/RtmpCCrbYX/remotes21e06ba141d2"’ returned error code 1
2: In system(cmd, intern = TRUE) :
  running command 'tar.exe -tf "C:\Users\Gerar\AppData\Local\Temp\RtmpCCrbYX\file21e077966d89.tar.gz"' had status 1
```

1) You could try to install it again the same way. Note, the data package is almost 2gb therefore it can take a while. 

We do have a demo online `http://34.91.67.53:3838/` which should make the waiting more bearable!

2) You could also try to download the repository as ZIP directly from github. Once the repository is downloaded, unzip the files and open the `R project` file in R studio. When you have opened the project in R studio press `Ctrl+Shift+B` and that should install the package.

If both options don't work, please let us know!

**Comment by ArisJimenez** [comment]
Hi,
 I have installed the packages by downloading them through the repository, but when I check using Ctrl + Shift + B and then the necessary packages, I add them by BiocManager, but I am still missing a package that is not available in this way, which is the "conquer.db"
While the other option throws me error.

**Comment by roderickslieker** [comment]
Hi,

Please note that the minimal required version for this is R-3.6.0. Which OS/ R version are you on? To get you started I will send you the source package (http://tiny.cc/r1iumz) which you can install using (link is valid for 7 days):

setwd("theworkingdirectorythefileisin")
install.packages("conquer.db_0.1.0.tar.gz", type="source", repos=NULL)

**Comment by ArisJimenez** [comment]
Hi,
thanks, it done!
My R version is 3.6.1. 
SO: Windows 10, version 1809

**Comment by roderickslieker** [comment]
Cool! Let me know if you come across any other errors.
